<?php

namespace App\Services;

use Illuminate\Contracts\Filesystem\Factory as FilesystemFactory;
use Illuminate\Http\UploadedFile;
use Illuminate\Validation\ValidationException;

/**
 * Stores resource images on disk and keeps only the path in the database.
 *
 * Filenames are generated by Laravel (a random 40-character hash plus the
 * extension derived from the file's real content), so a client-supplied name
 * never reaches the filesystem and path traversal is not possible.
 */
class ImageStorage
{
    public const DISK = 'public';

    /** Content types we are willing to serve back to a browser. */
    private const ALLOWED_MIME_TYPES = [
        'image/jpeg',
        'image/png',
        'image/webp',
    ];

    /** Megabytes. Generous for a photograph, mean for anything else. */
    private const MAX_MEGABYTES = 5;

    /**
     * The largest picture worth keeping.
     *
     * The size limit alone does not bound this. A 50000 × 50000 PNG of a flat
     * colour compresses to well under five megabytes and passes every other
     * rule here — and then every browser that opens the page has to decode
     * two and a half billion pixels. The server shrugs; the reader's tab
     * stops responding.
     *
     * 6000px is above any photograph a company would reasonably upload of a
     * hotel or a bus, and far below the point where decoding it hurts.
     */
    private const MAX_DIMENSION = 6000;

    /**
     * The validation rules for an uploaded image, in one place.
     *
     * Eight FormRequests need exactly this list. Written out in each of them,
     * the day one gains a rule the other seven silently keep the old one.
     *
     * @param  bool  $optional  true on update, where an absent field means
     *                          "leave the current image alone"
     * @return array<int, string>
     */
    public static function validationRules(bool $optional = false): array
    {
        return array_values(array_filter([
            $optional ? 'sometimes' : null,
            'nullable',
            // Real image, decided by content.
            'image',
            'mimes:jpeg,jpg,png,webp',
            'max:'.(self::MAX_MEGABYTES * 1024),
            'dimensions:max_width='.self::MAX_DIMENSION.',max_height='.self::MAX_DIMENSION,
        ]));
    }

    public function __construct(private readonly FilesystemFactory $filesystem) {}

    /**
     * @param  string  $directory  e.g. "packages"
     * @return string the stored path, relative to the disk root
     */
    public function store(UploadedFile $file, string $directory): string
    {
        $this->assertIsImage($file);

        return $file->store($directory, self::DISK);
    }

    /**
     * Stores the replacement first, then removes the old file, so a failed
     * upload cannot leave a record pointing at nothing.
     */
    public function replace(?string $existingPath, UploadedFile $file, string $directory): string
    {
        $path = $this->store($file, $directory);

        $this->delete($existingPath);

        return $path;
    }

    public function delete(?string $path): void
    {
        if ($path === null || $path === '') {
            return;
        }

        $this->filesystem->disk(self::DISK)->delete($path);
    }

    public function url(?string $path): ?string
    {
        if ($path === null || $path === '') {
            return null;
        }

        return $this->filesystem->disk(self::DISK)->url($path);
    }

    /**
     * Form Requests already apply `image` and `mimes` rules. This repeats the
     * check against the file's actual content because the service is also
     * reachable from the MCP layer, which must not be able to skip it.
     */
    private function assertIsImage(UploadedFile $file): void
    {
        $mime = $file->getMimeType();

        if (! in_array($mime, self::ALLOWED_MIME_TYPES, true)) {
            throw ValidationException::withMessages([
                'image' => __('messages.image_type'),
            ]);
        }

        // getimagesize() parses the header, which rejects a script that merely
        // claims an image content type.
        if (@getimagesize($file->getRealPath()) === false) {
            throw ValidationException::withMessages([
                'image' => __('messages.image_unreadable'),
            ]);
        }
    }
}
