import type { ApiEnvelope, Paginated, PaginationMeta } from '@hagamra/shared/types';

/**
 * The one place the panel talks to the backend from the browser.
 *
 * Requests go to this app's own /api/laravel proxy, same-origin, so the
 * session cookie rides along automatically and no token is ever handled in
 * JavaScript. The proxy attaches the real Authorization header.
 */

const BASE = '/api/laravel';

/**
 * A failed request, carrying enough for the UI to react sensibly: the status
 * to branch on and, for a 422, the per-field messages to show beside inputs.
 */
export class ApiError extends Error {
  readonly status: number;
  readonly errors: Record<string, string[]>;

  constructor(status: number, message: string, errors: Record<string, string[]> = {}) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
    this.errors = errors;
  }

  /** The first message for a field, for inline display under an input. */
  fieldError(field: string): string | undefined {
    return this.errors[field]?.[0];
  }

  get isValidation(): boolean {
    return this.status === 422;
  }

  get isForbidden(): boolean {
    return this.status === 403;
  }

  get isNotFound(): boolean {
    return this.status === 404;
  }

  get isUnauthenticated(): boolean {
    return this.status === 401;
  }
}

/**
 * Turns a status code into something a person can act on.
 *
 * The summary is always written here rather than passed through from the
 * backend. Laravel's own wording is English, so forwarding it would drop an
 * English sentence into an Arabic screen — and its 403 and 422 summaries say
 * nothing a reader could act on anyway ("This action is unauthorized.").
 *
 * The per-field messages under `errors` are a different matter and *are* shown
 * as the backend sends them: they name the field and the rule, and the backend
 * localises them from the Accept-Language header this client sends.
 *
 * A 500's message is never shown at all (spec §38, §51).
 */
function messageFor(status: number): string {
  switch (status) {
    case 401:
      return 'انتهت جلستك. يرجى تسجيل الدخول مرة أخرى.';
    case 403:
      return 'ليست لديك صلاحية لتنفيذ هذا الإجراء.';
    case 404:
      return 'العنصر المطلوب غير موجود.';
    case 422:
      return 'البيانات المُدخلة غير صحيحة. راجع الحقول المحدّدة.';
    case 429:
      return 'طلبات كثيرة جداً. يرجى المحاولة بعد قليل.';
    case 502:
      return 'تعذّر الوصول إلى الخادم. يرجى المحاولة مرة أخرى.';
    default:
      return status >= 500
        ? 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.'
        : 'تعذّر إتمام الطلب.';
  }
}

interface RequestOptions {
  method?: string;
  body?: unknown;
  query?: Record<string, unknown>;
  signal?: AbortSignal;
}

function buildQuery(query?: Record<string, unknown>): string {
  if (!query) return '';

  const params = new URLSearchParams();

  for (const [key, value] of Object.entries(query)) {
    // An absent filter and an empty one mean the same thing to the backend,
    // so neither is sent — it keeps URLs readable and caches aligned.
    if (value === undefined || value === null || value === '') continue;

    params.set(key, String(value));
  }

  const qs = params.toString();

  return qs ? `?${qs}` : '';
}

/**
 * Performs the call and returns the whole envelope, so list callers can reach
 * `meta` while everyone else just takes `data`.
 */
async function send<T>(
  path: string,
  options: RequestOptions = {},
): Promise<ApiEnvelope<T> & { meta?: PaginationMeta }> {
  const { method = 'GET', body, query, signal } = options;

  const isFormData = body instanceof FormData;

  const headers: Record<string, string> = { Accept: 'application/json' };

  // FormData must set its own Content-Type: the boundary is generated by the
  // browser, and overwriting the header makes the body unparseable.
  if (body !== undefined && !isFormData) {
    headers['Content-Type'] = 'application/json';
  }

  let response: Response;

  try {
    response = await fetch(`${BASE}/${path.replace(/^\/+/, '')}${buildQuery(query)}`, {
      method,
      headers,
      body: isFormData ? body : body !== undefined ? JSON.stringify(body) : undefined,
      signal,
      cache: 'no-store',
    });
  } catch (error) {
    // A cancelled request is the caller changing their mind, not a failure.
    if (error instanceof DOMException && error.name === 'AbortError') throw error;

    throw new ApiError(0, 'تعذّر الاتصال بالخادم. تحقّق من اتصالك بالشبكة.');
  }

  const envelope = (await response.json().catch(() => null)) as
    | (ApiEnvelope<T> & { meta?: PaginationMeta })
    | null;

  if (!response.ok || !envelope?.success) {
    const failure = envelope && !envelope.success ? envelope : null;

    throw new ApiError(
      response.status,
      messageFor(response.status),
      failure?.errors ?? {},
    );
  }

  return envelope;
}

async function request<T>(path: string, options: RequestOptions = {}): Promise<T> {
  const envelope = await send<T>(path, options);

  return (envelope as { data: T }).data;
}

/**
 * A list endpoint, returning rows and paging side by side.
 *
 * Paging always comes from the server (spec §42): the panel never pulls a
 * whole table down to slice it in the browser.
 */
async function paginate<T>(
  path: string,
  query?: Record<string, unknown>,
  signal?: AbortSignal,
): Promise<Paginated<T>> {
  const envelope = await send<T[]>(path, { query, signal });
  const items = (envelope as { data: T[] }).data;

  return {
    items,
    // Endpoints that return a plain array rather than a page (the owners of a
    // single company, for one) still need a shape the table can render.
    meta: envelope.meta ?? {
      current_page: 1,
      per_page: items.length,
      total: items.length,
      last_page: 1,
    },
  };
}

export const api = {
  get: <T>(path: string, query?: Record<string, unknown>, signal?: AbortSignal) =>
    request<T>(path, { query, signal }),

  list: <T>(path: string, query?: Record<string, unknown>, signal?: AbortSignal) =>
    paginate<T>(path, query, signal),

  post: <T>(path: string, body?: unknown) =>
    request<T>(path, { method: 'POST', body }),

  put: <T>(path: string, body?: unknown) =>
    request<T>(path, { method: 'PUT', body }),

  delete: <T>(path: string) =>
    request<T>(path, { method: 'DELETE' }),

  /**
   * Multipart write, for the forms that carry an image.
   *
   * PHP does not parse a multipart body on PUT, so an update is sent as a POST
   * with `_method=PUT` — Laravel reads that and routes it as an update. The
   * quirk is handled here so no calling component has to know about it.
   */
  upload: <T>(path: string, form: FormData, method: 'POST' | 'PUT' = 'POST') => {
    if (method === 'PUT') form.set('_method', 'PUT');

    return request<T>(path, { method: 'POST', body: form });
  },
};
